In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys
import os
import time
import numpy as np
from functools import partial
import itertools


In [3]:
import pydrake
import meshcat

from pydrake.all import BsplineTrajectoryThroughUnionOfHPolyhedra, IrisInConfigurationSpace, IrisOptions
from pydrake.common import FindResourceOrThrow
from pydrake.geometry import SceneGraph
from pydrake.math import RigidTransform, RollPitchYaw
from pydrake.multibody.optimization import CalcGridPointsOptions, Toppra
from pydrake.multibody.parsing import LoadModelDirectives, Parser, ProcessModelDirectives
from pydrake.multibody.plant import MultibodyPlant, AddMultibodyPlantSceneGraph
from pydrake.multibody.tree import RevoluteJoint
from pydrake.solvers.mathematicalprogram import MathematicalProgram, Solve
from pydrake.solvers.mosek import MosekSolver
from pydrake.systems.analysis import Simulator
from pydrake.systems.framework import DiagramBuilder
from pydrake.systems.primitives import TrajectorySource
from pydrake.trajectories import PiecewisePolynomial
from pydrake.all import Variable, Expression, RotationMatrix
from pydrake.all import MultibodyPositionToGeometryPose, ConnectMeshcatVisualizer, Role, Sphere
from pydrake.all import (
    ConvexSet, HPolyhedron, Hyperellipsoid,
    MathematicalProgram, Solve, le, IpoptSolver,
    Role, Sphere, VPolytope,
    Iris, IrisOptions, MakeIrisObstacles, Variable
)
from pydrake.all import (
    eq, SnoptSolver,
    Sphere, Ellipsoid, GeometrySet,
    RigidBody_, AutoDiffXd, initializeAutoDiff, InverseKinematics
)

import pydrake.symbolic as sym
import symbolic_parsing_helpers as symHelpers

from meshcat import Visualizer

import mcubes


# Setup meshcat
from meshcat.servers.zmqserver import start_zmq_server_as_subprocess
proc, zmq_url, web_url = start_zmq_server_as_subprocess(server_args=[])
proc2, zmq_url2, web_url2 = start_zmq_server_as_subprocess(server_args=[])

# Sporadically need to run `pkill -f meshcat`

from symbolic_parsing_helpers import generate_rationalize_trig_expr_rules
from symbolic_parsing_helpers import xreplace
from symbolic_parsing_helpers import NotRationalFunctionException
# from symbolic_parsing_helpers import rationalize_trig_expr
from pydrake.all import RationalFunction
snopt = SnoptSolver()
def xreplace(expr, rules):
        if isinstance(expr, float) or isinstance(expr, sym.Variable):
            return expr
        assert isinstance(expr, sym.Expression), expr
        for old, new in rules:
            if expr.EqualTo(old):
                return new
        ctor, old_args = expr.Deconstruct()
        new_args = [xreplace(e, rules) for e in old_args]
        return ctor(*new_args)

def MakeFromHPolyhedronOrEllipseSceneGraph(query, geom, expressed_in=None):
    shape = query.inspector().GetShape(geom)
    if isinstance(shape, (Sphere, Ellipsoid)):
        return Hyperellipsoid(query, geom, expressed_in)
    return HPolyhedron(query, geom, expressed_in)
def MakeFromVPolytopeOrEllipseSceneGraph(query, geom, expressed_in=None):
    shape = query.inspector().GetShape(geom)
    print(geom)
    if isinstance(shape, (Sphere, Ellipsoid)):
        return Hyperellipsoid(query, geom, expressed_in)
    return VPolytope(query, geom, expressed_in)


from pydrake.all import RationalForwardKinematics, FindBodyInTheMiddleOfChain

In [4]:
# prog = MathematicalProgram()

# x = [sym.Variable("x{}".format(i)) for i in range(3)]
# prog.AddIndeterminates(x)
# poly, Q = prog.NewSosPolynomial(sym.Variables(x),2)
# poly.SetIndeterminates(sym.Variables(x))
# print(prog)
# prog.AddSosConstraint(poly)
# print(prog)

In [5]:
x = sym.Variable('x')
r1 = RationalFunction(sym.Polynomial(2*x+1), sym.Polynomial(x**2-1))
r2 = RationalFunction(sym.Polynomial(2*x+1), sym.Polynomial(x**2-1))
r3 = RationalFunction(sym.Polynomial(2*x+1), sym.Polynomial(x+1)*sym.Polynomial(x-1))
r4 = RationalFunction(sym.Polynomial(2*x+1), sym.Polynomial(x+1))

print(r1+r2)
print(r1+r3)
print(r1+r4)

(2*1 + 4*x) / (-1*1 + 1*x^2)
(2*1 + 4*x) / (-1*1 + 1*x^2)
(1*x + 3*x^2 + 2*x^3) / (-1*1 + -1*x + 1*x^2 + 1*x^3)


# Build simulation Environment

In [6]:
simple_collision = True
# gripper_welded = True

vis = Visualizer(zmq_url=zmq_url)
vis.delete()
vis2 = Visualizer(zmq_url=zmq_url2)
vis2.delete()

display(vis.jupyter_cell())

builder = DiagramBuilder()
plant, scene_graph = AddMultibodyPlantSceneGraph(builder, time_step=0.001)
parser = Parser(plant)
parser.package_map().Add( "wsg_50_description", os.path.dirname(FindResourceOrThrow(
            "drake/manipulation/models/wsg_50_description/package.xml")))

directives_file = FindResourceOrThrow("drake/sandbox/planar_iiwa_simple_collision_welded_gripper.yaml") \
    if simple_collision else FindResourceOrThrow("drake/sandbox/planar_iiwa_dense_collision_welded_gripper.yaml")
directives = LoadModelDirectives(directives_file)
models = ProcessModelDirectives(directives, plant, parser)

q0 = [-0.2, -1.2, 1.6]
index = 0
for joint_index in plant.GetJointIndices(models[0].model_instance):
    joint = plant.get_mutable_joint(joint_index)
    if isinstance(joint, RevoluteJoint):
        joint.set_default_angle(q0[index])
        index += 1

plant.Finalize()

visualizer = ConnectMeshcatVisualizer(builder, scene_graph, zmq_url=zmq_url, delete_prefix_on_load=False)

diagram = builder.Build()
visualizer.load()
context = diagram.CreateDefaultContext()
plant_context = plant.GetMyContextFromRoot(context)
diagram.Publish(context)
query = scene_graph.get_query_output_port().Eval(scene_graph.GetMyContextFromRoot(context))


    
ik = InverseKinematics(plant, plant_context)
collision_constraint = ik.AddMinimumDistanceConstraint(0.001, 0.01)


inspector = query.inspector()
pairs = inspector.GetCollisionCandidates()


geom_ids = inspector.GetGeometryIds(GeometrySet(inspector.GetAllGeometryIds()), Role.kProximity)
HPolyhedronSets = {geom:MakeFromHPolyhedronOrEllipseSceneGraph(query, geom, inspector.GetFrameId(geom)) for geom in geom_ids}
VPolyhedronSets = {geom:MakeFromVPolytopeOrEllipseSceneGraph(query, geom, inspector.GetFrameId(geom)) for geom in geom_ids}



body_indexes_by_geom_id = {geom:
                           plant.GetBodyFromFrameId(inspector.GetFrameId(geom)).index() for geom in geom_ids} 

You can open the visualizer by visiting the following URL:
http://127.0.0.1:7000/static/
You can open the visualizer by visiting the following URL:
http://127.0.0.1:7001/static/


Connecting to meshcat-server at zmq_url=tcp://127.0.0.1:6000...
You can open the visualizer by visiting the following URL:
http://127.0.0.1:7000/static/
Connected to meshcat-server.
<GeometryId value=71>
<GeometryId value=79>
<GeometryId value=113>
<GeometryId value=115>
<GeometryId value=117>
<GeometryId value=85>
<GeometryId value=91>


In [7]:
VPolyhedronSets = {geom:MakeFromVPolytopeOrEllipseSceneGraph(query, geom, inspector.GetFrameId(geom))
                   for geom in geom_ids}
print(geom_ids)


<GeometryId value=71>
<GeometryId value=79>
<GeometryId value=113>
<GeometryId value=115>
<GeometryId value=117>
<GeometryId value=85>
<GeometryId value=91>
{<GeometryId value=71>, <GeometryId value=79>, <GeometryId value=113>, <GeometryId value=115>, <GeometryId value=117>, <GeometryId value=85>, <GeometryId value=91>}


In [8]:
def visualize_trajectory(traj):
    builder = DiagramBuilder()

    scene_graph = builder.AddSystem(SceneGraph())
    plant = MultibodyPlant(time_step=0.0)
    plant.RegisterAsSourceForSceneGraph(scene_graph)
    parser = Parser(plant)
    parser.package_map().Add( "wsg_50_description", os.path.dirname(FindResourceOrThrow(
                "drake/manipulation/models/wsg_50_description/package.xml")))

    directives_file = FindResourceOrThrow("drake/sandbox/planar_iiwa_simple_collision_welded_gripper.yaml") \
        if simple_collision else FindResourceOrThrow("drake/sandbox/planar_iiwa_dense_collision_welded_gripper.yaml")
    directives = LoadModelDirectives(directives_file)
    models = ProcessModelDirectives(directives, plant, parser)

    q0 = [-0.2, -1.2, 1.6]
    index = 0
    for joint_index in plant.GetJointIndices(models[0].model_instance):
        joint = plant.get_mutable_joint(joint_index)
        if isinstance(joint, RevoluteJoint):
            joint.set_default_angle(q0[index])
            index += 1

    plant.Finalize()

    to_pose = builder.AddSystem(MultibodyPositionToGeometryPose(plant))
    builder.Connect(to_pose.get_output_port(), scene_graph.get_source_pose_port(plant.get_source_id()))

    traj_system = builder.AddSystem(TrajectorySource(traj))
    builder.Connect(traj_system.get_output_port(), to_pose.get_input_port())

    meshcat = ConnectMeshcatVisualizer(builder, scene_graph, zmq_url=zmq_url)

    vis_diagram = builder.Build()

    simulator = Simulator(vis_diagram)
    meshcat.start_recording()
    simulator.AdvanceTo(traj.end_time())
    meshcat.publish_recording()
    with open("/tmp/spp_shelves.html", "w") as f:
        f.write(meshcat.vis.static_html())


# Construct Rational Kinematics

In [9]:
forward_kin = RationalForwardKinematics(plant)
q_star = np.zeros(forward_kin.t().shape[0])
t = forward_kin.t()
def convert_RationalForwardPoseList_to_TransformExpressionList(pose_list):
    ret = []
    for p in pose_list:
        ret.append(p.asRigidTransformExpr())
    return ret

def convert_t_to_q(t):
    q =np.arctan2(2*t/(1+t**2), (1-t**2)/(1+t**2))
    return q

def convert_q_to_t(t):
    q =np.tan(t/2)
    return q

def eval_cons(q0, q1, q2, c, tol):
        return 1-1*float(c.evaluator().CheckSatisfied([q0, q1, q2], tol))
    
col_func_handle = partial(eval_cons, c=collision_constraint, tol=0.01)


def eval_cons_rational(t0, t1, t2, c, tol):
        q = convert_t_to_q(np.array([t0, t1, t2])) 
        return 1-1*float(c.evaluator().CheckSatisfied(q, tol))

col_func_handle_rational = partial(eval_cons_rational, c=collision_constraint, tol=0.01)
link_poses_by_body_index_rat_pose = forward_kin.CalcLinkPoses(q_star, 
                                                         plant.world_body().index())
link_poses_by_body_index_multilinear_pose = forward_kin.CalcLinkPosesAsMultilinearPolynomials(q_star, 
                                                         plant.world_body().index())

X_WA_list = convert_RationalForwardPoseList_to_TransformExpressionList(link_poses_by_body_index_rat_pose)
X_WA_multilinear_list = [(r.rotation(), r.translation()) for r in link_poses_by_body_index_multilinear_pose]
geomA, geomB = next(iter(pairs))
index = FindBodyInTheMiddleOfChain(plant, body_indexes_by_geom_id[geomA], body_indexes_by_geom_id[geomB])
print(index)

BodyIndex(4)


In [10]:
q_low = plant.GetPositionLowerLimits()
q_high = plant.GetPositionUpperLimits()
t_low = forward_kin.ComputeTValue(q_low,q_star)
t_high = forward_kin.ComputeTValue(q_high,q_star)
print(t_low)
print(t_high)

[-1.73205081 -1.73205081 -1.73205081]
[1.73205081 1.73205081 1.73205081]


## Marching Cubes Obstacles

In [11]:
N = 50
vertices, triangles = mcubes.marching_cubes_func(tuple(t_low), tuple(t_high), N, N, N, col_func_handle_rational, 0.5)
vis2["collision_constraint"].set_object(
            meshcat.geometry.TriangularMeshGeometry(vertices, triangles),
            meshcat.geometry.MeshLambertMaterial(color=0xff0000, wireframe=True))
# q = q0.copy()
# showres(q)

# Define Iris In T-Space

In [12]:
#  Now IRIS in configuration space, using dReal to solve for the growth volume
# through the nonconvex kinematics.

from pydrake.all import (
    eq, SnoptSolver,
    Sphere, Ellipsoid, GeometrySet,
    RigidBody_, AutoDiffXd, initializeAutoDiff,
)


def TangentPlane(self, point):
    a = 2 * self.A().T @ self.A() @ (point - self.center())
    a = a / np.linalg.norm(a)
    b = a.dot(point)
    return a, b

Hyperellipsoid.TangentPlane = TangentPlane


query = scene_graph.get_query_output_port().Eval(scene_graph.GetMyContextFromRoot(context))

sym_plant = plant.ToSymbolic()
sym_context = sym_plant.CreateDefaultContext()

# For SNOPT test.
autodiff_plant = plant.ToAutoDiffXd()
autodiff_context = autodiff_plant.CreateDefaultContext()
snopt = SnoptSolver()


dReal_polytope_tol = 1

def CheckVolume(E, bodyA, bodyB, setA, setB, A, b, volume):
    prog = MathematicalProgram()
    q = prog.NewContinuousVariables(plant.num_positions(), "q")
    prog.AddBoundingBoxConstraint(lb, ub, q)
    prog.AddLinearConstraint(A, b-np.inf, b, q)
    p_AA =  prog.NewContinuousVariables(3, "p_AA")
    p_BB = prog.NewContinuousVariables(3, "p_BB")
    if volume < np.inf:
        prog.AddConstraint((q-E.center()).T @ E.A().T @ E.A() @ (q-E.center()) <= volume)
    setA.AddPointInSetConstraints(prog, p_AA)
    setB.AddPointInSetConstraints(prog, p_BB)

    sym_plant.SetPositions(sym_context, q)
    X_WA = sym_plant.EvalBodyPoseInWorld(sym_context, bodyA)
    X_WB = sym_plant.EvalBodyPoseInWorld(sym_context, bodyB)
    # Add +0 pending https://github.com/RobotLocomotion/drake/issues/15216
    print(type(X_WA))
    p_WA = X_WA.multiply(p_AA+0)
    p_WB = X_WB.multiply(p_BB+0)
    prog.AddConstraint(eq(p_WA, p_WB))
    prog.SetSolverOption(dReal.id(), "precision", .9*dReal_polytope_tol)
    result = dReal.Solve(prog)
    return result.is_success(), result.GetSolution(q)


def GrowthVolume(E, bodyA, bodyB, setA, setB, A, b, guess=None):
    prog = MathematicalProgram()
    q = prog.NewContinuousVariables(plant.num_positions(), "q")

    if guess is not None:
        prog.SetInitialGuess(q, guess)

    prog.AddLinearConstraint(A, b-np.inf, b, q)
    p_AA = prog.NewContinuousVariables(3, "p_AA")
    p_BB = prog.NewContinuousVariables(3, "p_BB")
    setA.AddPointInSetConstraints(prog, p_AA)
    setB.AddPointInSetConstraints(prog, p_BB)
    prog.AddQuadraticErrorCost(E.A().T @ E.A(), E.center(), q)

    # TODO: Remove these.  They're for debugging only.
    #set_meshcat_object(vis['setA'],setA)
    #set_meshcat_object(vis['setB'],setB)
    print(type(p_AA[0]))
    if isinstance(bodyA, RigidBody_[AutoDiffXd]):
        # TODO: Update this to use MBP<double> and Jacobians if I'm going to keep it.
        def kinematics_constraint(vars):
            p_AA, p_BB, q = np.split(vars,[3,6])
            autodiff_plant.SetPositions(autodiff_context, q)
            X_WA = autodiff_plant.EvalBodyPoseInWorld(autodiff_context, bodyA)
            X_WB = autodiff_plant.EvalBodyPoseInWorld(autodiff_context, bodyB)
            p_WA = X_WA.multiply(p_AA)
            p_WB = X_WB.multiply(p_BB)
            return p_WA - p_WB
        prog.AddConstraint(kinematics_constraint, lb=[0,0,0], ub=[0,0,0],
                           vars=np.concatenate((p_AA,p_BB,q)))
        result = snopt.Solve(prog)

    else:
        # TODO: Construct these symbolic expressions once per body outside this method.
        # But I would have to substitute in the new q each time.
        # Better is to construct the prog once for each pair, and just update the cost?
        sym_plant.SetPositions(sym_context, q)
        X_WA = sym_plant.EvalBodyPoseInWorld(sym_context, bodyA)
        X_WB = sym_plant.EvalBodyPoseInWorld(sym_context, bodyB)
        # Add +0 pending https://github.com/RobotLocomotion/drake/issues/15216
        p_WA = X_WA.multiply(p_AA+0)
        
        p_WB = X_WB.multiply(p_BB+0)
        prog.AddConstraint(eq(p_WA, p_WB))
        result = snopt.Solve(prog)
        #result = dReal.Solve(prog)

    return result.is_success(), result.get_optimal_cost(), result.GetSolution(q)

def iris_cspace(query, point, require_containment_points=[], termination_threshold=2e-2, iteration_limit=100):
#     vis = Visualizer(zmq_url=zmq_url)
#     set_meshcat_object(vis['sample'], point, color=0x99dd99)

    ellipsoid_epsilon = 1e-1
    dim = plant.num_positions()
    lb = plant.GetPositionLowerLimits()
    ub = plant.GetPositionUpperLimits()
#     assert dim == 3 # need to update the volume once this changes
    volume_of_unit_sphere = 4.0*np.pi/3.0
    E = Hyperellipsoid(np.eye(3)/ellipsoid_epsilon, point)
#     set_meshcat_object(vis['ellipse'], E)
    best_volume = ellipsoid_epsilon**dim * volume_of_unit_sphere

    inspector = query.inspector()
    pairs = inspector.GetCollisionCandidates()

    P = HPolyhedron.MakeBox(lb, ub)
    A = np.vstack((P.A(), np.zeros((10*len(pairs),3))))  # allow up to 10 faces per pair.
    b = np.concatenate((P.b(), np.zeros(10*len(pairs))))

    geom_ids = inspector.GetGeometryIds(GeometrySet(inspector.GetAllGeometryIds()), Role.kProximity)
    sets = {geom:MakeFromHPolyhedronOrEllipseSceneGraph(query, geom, inspector.GetFrameId(geom)) for geom in geom_ids}

    use_autodiff = False
    use_dReal = False
    ad_bodies = {geom:autodiff_plant.GetBodyFromFrameId(inspector.GetFrameId(geom)) for geom in geom_ids}
    sym_bodies = {geom:sym_plant.GetBodyFromFrameId(inspector.GetFrameId(geom)) for geom in geom_ids}
    if use_autodiff:
        bodies = ad_bodies
    else:
        bodies = sym_bodies
    print
    iteration = 0
    num_faces = 2*len(lb)
    while True:
        ## Find separating hyperplanes

        for geomA, geomB in pairs:
            print(f"geomA={inspector.GetName(geomA)}, geomB={inspector.GetName(geomB)}")
            # Run snopt at the beginning
            while True:
                success, growth, qstar = GrowthVolume(E,
                    bodies[geomA], bodies[geomB],
                    sets[geomA], sets[geomB], A[:num_faces,:], b[:num_faces] - dReal_polytope_tol, point)
                if success:
                    print(f"snopt_example={qstar}, growth = {growth}")
                    # Add a face to the polytope
                    A[num_faces,:], b[num_faces] = E.TangentPlane(qstar)
                    num_faces += 1
                else:
                    break

            if use_dReal:
                tries = 0
                while True:
                    reachable, counter_example = CheckVolume(
                        E, sym_bodies[geomA], sym_bodies[geomB], sets[geomA], sets[geomB],
                        A[:num_faces,:], b[:num_faces] - dReal_polytope_tol, np.inf)
                    if not reachable:
                        print("unreachable")
                        break
                    else:
                        z = E.A() @ (counter_example - E.center())
                        dreal_growth = z.dot(z)
                        print(f"counter_example = {counter_example}, growth = {dreal_growth}")
                        success, growth, qstar = GrowthVolume(E,
                            bodies[geomA], bodies[geomB],
                            sets[geomA], sets[geomB], A[:num_faces,:], b[:num_faces] - dReal_polytope_tol, counter_example)
                        if success:
                            print(f"snopt_example={qstar}, growth = {growth}")
                            # Add a face to the polytope
                            A[num_faces,:], b[num_faces] = E.TangentPlane(qstar)
                            num_faces += 1
                        if np.all(A[:num_faces,:] @ counter_example <= b[:num_faces] - dReal_polytope_tol):
                            # Then also add the counter-example
                            A[num_faces,:], b[num_faces] = E.TangentPlane(counter_example)
                            num_faces += 1
                    tries += 1

        if any([np.any(A[:num_faces,:] @ q > b[:num_faces]) for q in require_containment_points]):
            print("terminating because a required containment point would have not been contained")
            break

        P = HPolyhedron(A[:num_faces,:],b[:num_faces])
#         set_meshcat_object(vis[f'polytope'], P, wireframe=True)

        E = P.MaximumVolumeInscribedEllipsoid()
#         set_meshcat_object(vis[f'ellipse'], E)
        print(iteration)

        iteration += 1
        if iteration >= iteration_limit:
            break

        volume = volume_of_unit_sphere / np.linalg.det(E.A())
        if volume - best_volume <= termination_threshold:
            break
        best_volume = volume

    return P


In [13]:
def GrowthVolumeRational(E, X_WA, X_WB, setA, setB, A, b, guess=None):
    snopt = SnoptSolver()
    prog = MathematicalProgram()
    t = forward_kin.t()
    prog.AddDecisionVariables(t)
    
    if guess is not None:
        prog.SetInitialGuess(t, guess)

    prog.AddLinearConstraint(A, b-np.inf, b, t)
    p_AA = prog.NewContinuousVariables(3, "p_AA")
    p_BB = prog.NewContinuousVariables(3, "p_BB")
    setA.AddPointInSetConstraints(prog, p_AA)
    setB.AddPointInSetConstraints(prog, p_BB)
    prog.AddQuadraticErrorCost(E.A().T @ E.A(), E.center(), t)

    p_WA = X_WA.multiply(p_AA+0)

    p_WB = X_WB.multiply(p_BB+0)

    prog.AddConstraint(eq(p_WA, p_WB))
    result = snopt.Solve(prog)
    return result.is_success(), result.get_optimal_cost(), result.GetSolution(t)


In [14]:
def iris_rational_space(query, point, require_containment_points=[], termination_threshold=2e-2, iteration_limit=100):
    dReal_polytope_tol = 1e-2
    ellipsoid_epsilon = 1e-1
    dim = plant.num_positions()
    lb = plant.GetPositionLowerLimits()
    rational_lb = forward_kin.ComputeTValue(lb, q_star)
    ub = plant.GetPositionUpperLimits()
    rational_ub = forward_kin.ComputeTValue(ub, q_star)
    volume_of_unit_sphere = 4.0*np.pi/3.0
    E = Hyperellipsoid(np.eye(3)/ellipsoid_epsilon, point)
    best_volume = ellipsoid_epsilon**dim * volume_of_unit_sphere
    
    link_poses_by_body_index_rat_pose = forward_kin.CalcLinkPoses(q_star, 
                                                         plant.world_body().index())
    X_WA_list = convert_RationalForwardPoseList_to_TransformExpressionList(link_poses_by_body_index_rat_pose)

    inspector = query.inspector()
    pairs = inspector.GetCollisionCandidates()

    P = HPolyhedron.MakeBox(rational_lb, rational_ub)
    A = np.vstack((P.A(), np.zeros((10*len(pairs),3))))  # allow up to 10 faces per pair.
    b = np.concatenate((P.b(), np.zeros(10*len(pairs))))

    geom_ids = inspector.GetGeometryIds(GeometrySet(inspector.GetAllGeometryIds()), Role.kProximity)
    sets = {geom:MakeFromHPolyhedronOrEllipseSceneGraph(query, geom, inspector.GetFrameId(geom)) for geom in geom_ids}
    body_indexes_by_geom_id = {geom:
                               plant.GetBodyFromFrameId(inspector.GetFrameId(geom)).index() for geom in geom_ids} 
    
    #Turn onto true to certify regions using SOS at each iteration.
    certify = False
    # refine polytopes if not certified collision free
    refine = False and certify
        
    iteration = 0
    num_faces = 2*len(lb)
    while True:
        ## Find separating hyperplanes

        for geomA, geomB in pairs:
            print(f"geomA={inspector.GetName(geomA)}, geomB={inspector.GetName(geomB)}")
            # Run snopt at the beginning
            while True:
                X_WA = X_WA_list[int(body_indexes_by_geom_id[geomA])]
                X_WB = X_WA_list[int(body_indexes_by_geom_id[geomB])]
                success, growth, qstar = GrowthVolumeRational(E,
                    X_WA, X_WB,
                    sets[geomA], sets[geomB], 
                    A[:num_faces,:], b[:num_faces] - dReal_polytope_tol, 
                    point)
                if success:
                    print(f"snopt_example={qstar}, growth = {growth}")
                    # Add a face to the polytope
                    A[num_faces,:], b[num_faces] = E.TangentPlane(qstar)
                    num_faces += 1
                else:
                    break

            if certify:
                pass
            

        if any([np.any(A[:num_faces,:] @ t > b[:num_faces]) for t in require_containment_points]):
            print("terminating because a required containment point would have not been contained")
            break

        P = HPolyhedron(A[:num_faces,:],b[:num_faces])

        E = P.MaximumVolumeInscribedEllipsoid()
        print(iteration)

        iteration += 1
        if iteration >= iteration_limit:
            break

        volume = volume_of_unit_sphere / np.linalg.det(E.A())
        if volume - best_volume <= termination_threshold:
            break
        best_volume = volume

    return P

In [15]:
seed_points = np.tan(np.array([[0.0, -2.016, 1.975], # in tight
                        [-1, -2, 0.5],        # neutral pose
                        [0.3, -0.8, 0.5],     # above shelf
                        [0.25, -1.6, -0.25],  # in shelf 1
                        [0.07, -1.8, -0.2],   # leaving shelf 1
                        [-0.1, -2, -0.3]])    # out of shelf 1
                        /2)
for i in range(seed_points.shape[0]):
    vis2['seedpoints']["seedpoint"+str(i)].set_object(
                meshcat.geometry.Sphere(0.1), meshcat.geometry.MeshLambertMaterial(color=0xFFB900))
    vis2['seedpoints']["seedpoint"+str(i)].set_transform(
                meshcat.transformations.translation_matrix(seed_points[i,:]))

# traj = PiecewisePolynomial.FirstOrderHold(np.array([0, 1]), np.array([seed_points[4], seed_points[1]]).T)
# visualize_trajectory(traj)

In [16]:

regions = []
ellipses = []
for i in range(seed_points.shape[0]):
    
    start_time = time.time()
    hpoly = iris_rational_space(query, seed_points[i,:], require_containment_points=[seed_points[i,:]], iteration_limit=100)
#     hpoly = iris_cspace(query, seed_points[i,:], require_containment_points=[seed_points[i,:]], iteration_limit=100)
    ellipse = hpoly.MaximumVolumeInscribedEllipsoid()
    print("Time: %6.2f \tVolume: %6.2f \tCenter:" % (time.time() - start_time, ellipse.Volume()),
          ellipse.center(), flush=True)
    regions.append(hpoly)
    ellipses.append(ellipse)

print("SUCCESS")

geomA=iiwa::link7, geomB=shelves::top
snopt_example=[ 0.25686152 -0.44650254  1.37305101], growth = 138.27790339845825
geomA=iiwa::link7, geomB=wsg::right_collision
geomA=wsg::left_collision, geomB=wsg::right_collision
geomA=wsg::right_collision, geomB=shelves::shelf_upper
snopt_example=[ 0.14471298 -0.66482365  0.73909564], growth = 147.06126401711242
snopt_example=[ 0.26684134 -0.53520202  0.93115289], growth = 151.49619658550938
geomA=wsg::body_collision, geomB=shelves::top
geomA=wsg::body_collision, geomB=shelves::shelf_upper
snopt_example=[ 0.32551918 -0.53379534  1.10297422], growth = 138.142516784699
geomA=wsg::left_collision, geomB=shelves::top
geomA=wsg::right_collision, geomB=shelves::top
geomA=iiwa::link7, geomB=shelves::shelf_lower
snopt_example=[ 0.5119587  -0.80097613  1.4041356 ], growth = 88.94239682323666
geomA=wsg::body_collision, geomB=shelves::shelf_lower
geomA=wsg::left_collision, geomB=shelves::shelf_lower
snopt_example=[ 0.27896158 -0.8160305   0.60048261], growt

geomA=wsg::body_collision, geomB=shelves::shelf_upper
snopt_example=[ 0.14420559 -1.25506828 -0.25494605], growth = 3.585332366144627
geomA=wsg::left_collision, geomB=shelves::top
snopt_example=[-0.04434811 -1.22664273 -0.13630201], growth = 0.8715330056431299
snopt_example=[-0.01399985 -0.99501865  0.0385244 ], growth = 9.19832182806266
geomA=wsg::right_collision, geomB=shelves::top
geomA=iiwa::link7, geomB=shelves::shelf_lower
geomA=wsg::body_collision, geomB=shelves::shelf_lower
geomA=wsg::left_collision, geomB=shelves::shelf_lower
geomA=wsg::right_collision, geomB=shelves::shelf_lower
geomA=iiwa::link7, geomB=wsg::left_collision
geomA=iiwa::link7, geomB=shelves::shelf_upper
geomA=wsg::left_collision, geomB=shelves::shelf_upper
0
geomA=iiwa::link7, geomB=shelves::top
geomA=iiwa::link7, geomB=wsg::right_collision
geomA=wsg::left_collision, geomB=wsg::right_collision
geomA=wsg::right_collision, geomB=shelves::shelf_upper
geomA=wsg::body_collision, geomB=shelves::top
geomA=wsg::body_co

# Choose poly to cert

In [17]:
print(regions)
poly_to_cert_safe = regions[2]
Atmp = poly_to_cert_safe.A()
btmp = poly_to_cert_safe.b()
poly_to_cert_safe = HPolyhedron(Atmp, btmp-0.3)


poly_to_cert_unsafe = regions[0]
Atmp = poly_to_cert_unsafe.A()
btmp = poly_to_cert_unsafe.b()
poly_to_cert_unsafe = HPolyhedron(Atmp, btmp+0.3)



[<pydrake.geometry.optimization.HPolyhedron object at 0x7f857418d1b0>, <pydrake.geometry.optimization.HPolyhedron object at 0x7f8574184470>, <pydrake.geometry.optimization.HPolyhedron object at 0x7f857419a6b0>, <pydrake.geometry.optimization.HPolyhedron object at 0x7f84bd1e67f0>, <pydrake.geometry.optimization.HPolyhedron object at 0x7f857419a130>, <pydrake.geometry.optimization.HPolyhedron object at 0x7f85845c0570>]


## Plot Regions

In [18]:
def inpolycheck(q0,q1,q2, A, b):
    q = np.array([q0, q1, q2])
    res = np.min(1.0*(A@q-b<=0))
    #print(res)
    return res
eps = 0.5
meshes = []
col1 = 0x002BFF
col2 = 0x3EFF00 
idx = 0
step = 1/(1.0*len(regions))
R = np.array([[1, 0, 0],[0, 0, 1],[0,1, 0]])
order = (0,1,2)
for i, region in enumerate(regions):
    A = region.A()[:,order]
    b = region.b()

    col_hand = partial(inpolycheck, A=A, b=b)
    vertices, triangles = mcubes.marching_cubes_func(tuple(t_low-eps), tuple(t_high+eps), 50, 50, 50, col_hand, 0.5)

    regstr = "regions" +str(idx)
    ellstr = "ellipse" +str(idx)
    mat = meshcat.geometry.MeshLambertMaterial(color= int((1-idx*step)*col1 + idx*step*col2), wireframe=True)
    vis2['regions'][regstr].set_object(
            meshcat.geometry.TriangularMeshGeometry(vertices, triangles),
            mat)


    
    idx+=1
A_poly = poly_to_cert_safe.A()         
b_poly = poly_to_cert_safe.b() 
col_hand = partial(inpolycheck, A=A_poly, b=b_poly)
Nhere = 75
vertices, triangles = mcubes.marching_cubes_func(tuple(t_low-eps), tuple(t_high+eps), Nhere, Nhere, Nhere, col_hand, 0.5)
mat = meshcat.geometry.MeshLambertMaterial(color= int((1-idx*step)*col1 + idx*step*col2), wireframe=True)
mat.opacity = 0.3
vis2['poly_to_cert_safe'].set_object(
            meshcat.geometry.TriangularMeshGeometry(vertices, triangles),
            mat)
    
A_poly = poly_to_cert_unsafe.A()         
b_poly = poly_to_cert_unsafe.b() 
col_hand = partial(inpolycheck, A=A_poly, b=b_poly)
vertices, triangles = mcubes.marching_cubes_func(tuple(t_low), tuple(t_high), Nhere, Nhere, Nhere, col_hand, 0.5)
mat = meshcat.geometry.MeshLambertMaterial(color= int((1-idx*step)*col1 + idx*step*col2), wireframe=True)
mat.opacity = 0.3
vis2['poly_to_cert_unsafe'].set_object(
            meshcat.geometry.TriangularMeshGeometry(vertices, triangles),
            mat)

# Certify the Regions

In [19]:
def construct_first_order_separating_hyperplane(prog, t, plane_name = ''):
    if plane_name != '':
        plane_name = '_'+plane_name
    a_A_coeffs = prog.NewContinuousVariables(3, t.shape[0], 'a_A'+plane_name)
    a_b_offset = prog.NewContinuousVariables(3, 'a_b'+plane_name)
    a_poly = a_A_coeffs@t+a_b_offset
    
    b_A_coeffs = prog.NewContinuousVariables(1, t.shape[0], 'b_A'+plane_name)
    b_b_offset = prog.NewContinuousVariables(1, 'b_b'+plane_name)
    b_poly = b_A_coeffs@t+b_b_offset
    
    for i, p in enumerate(a_poly):
        a_poly[i] = sym.Polynomial(p)
        a_poly[i].SetIndeterminates(sym.Variables(t))
    b_poly = sym.Polynomial(b_poly[0])
    b_poly.SetIndeterminates(sym.Variables(t))
    
    dec_vars = [*a_A_coeffs.flatten().tolist(), *a_b_offset.tolist(), *b_A_coeffs.flatten().tolist(), *b_b_offset.tolist()]
    return prog, a_poly, b_poly, dec_vars


def putinarPsatConstraint(prog, p, t,  
                         poly_to_cert, lagrange_mult_degree = 2, var_epsilon = None):
    A = poly_to_cert.A()
    b = poly_to_cert.b()
    n = b.shape[0]
    if var_epsilon is None:
        var_epsilon = np.zeros(n)
    lagrange_poly, Q = prog.NewSosPolynomial(sym.Variables(t), lagrange_mult_degree+2)
    lagrange_poly.SetIndeterminates(sym.Variables(t))
    prog.AddSosConstraint(lagrange_poly)
    constraint_poly = lagrange_poly
    for i in range(n):
        lagrange_poly, Q = prog.NewSosPolynomial(sym.Variables(t), lagrange_mult_degree)
        lagrange_poly.SetIndeterminates(sym.Variables(t))
        prog.AddSosConstraint(lagrange_poly)
        constraint_poly += lagrange_poly*sym.Polynomial(b[i]-var_epsilon[i]-A[i,:]@t)
    constraint_poly.SetIndeterminates(sym.Variables(t))
    prog.AddEqualityConstraintBetweenPolynomials(constraint_poly, p)
#     prog.AddSosConstraint(p-constraint_poly)
    return prog


def makeBodyHyperplaneSidePolynomials(prog, a_plane_poly, b_plane_poly,
                          VPoly, R_WA, p_WA, t, poly_to_cert, leq_or_geq,
                          lagrange_mult_degree = 2, var_epsilon = None, base_point_as_multilinear_poly = None):
    num_verts = VPoly.vertices().shape[1]

    vertex_pos = R_WA@(VPoly.vertices())+ np.repeat(p_WA[:, np.newaxis],num_verts,1)
    zero_poly = sym.Polynomial(0)
    if base_point_as_multilinear_poly is None:
        base_point_as_multilinear_poly = np.array([zero_poly for i in range(3)])
    
    centered_pos = vertex_pos - np.repeat(base_point_as_multilinear_poly[:, np.newaxis],num_verts,1)
      
  
    #a^T(x-y) < 1 condition
#     dens = np.ndarray(shape = vertex_pos.shape,dtype = object)
#     for r, row in enumerate(centered_pos):
#         for c, v in enumerate(row):
#             centered_pos[r,c] = forward_kin.ConvertMultilinearPolynomialToRationalFunction(v)
#             dens[r,c] = centered_pos[r,c].denominator()
            

#     for c in range(dens.shape[1]):
#         for r in range(dens.shape[0]-1):
#             if not dens[r,c].EqualTo(dens[r+1,c]):
#                 raise ValueError("problem")
#     #check matching denominator
#     plane_rats = a_plane_poly.dot(centered_pos)
#     plane_polys = np.array([None for _ in plane_rats])
#     prog_eps = 1e-12
#     for i, p in enumerate(plane_rats):
#         p.SetIndeterminates(sym.Variables(t))
        
#         if leq_or_geq == 'leq':
#             plane_polys[i] = p.denominator()-p.numerator() #(b_plane_poly-prog_eps)*p.denominator()-p.numerator()
#         elif leq_or_geq == 'geq':
#             plane_polys[i] = p.numerator()-p.denominator()
#         else:
#             raise ValueError("leq_or_geq arg must be leq or geq not {}".format(leq_or_geq))  

            
    ##a^Ty<b condition
    dens = np.ndarray(shape = vertex_pos.shape,dtype = object)
    for i, row in enumerate(vertex_pos):
        
        for j, v in enumerate(row):
            vertex_pos[i,j] = forward_kin.ConvertMultilinearPolynomialToRationalFunction(v)
            dens[i,j] = vertex_pos[i,j].denominator()

    for c in range(dens.shape[1]):
        for r in range(dens.shape[0]-1):
            if not dens[r,c].EqualTo(dens[r+1,c]):
                raise ValueError("problem")
            
    plane_rats = a_plane_poly.dot(vertex_pos)
    plane_polys = np.array([None for _ in plane_rats])
    prog_eps = 1e-12
    for i, p in enumerate(plane_rats):
        p.SetIndeterminates(sym.Variables(t))
        
        if leq_or_geq == 'leq':
            plane_polys[i] = -(p.numerator()+(b_plane_poly-1)*p.denominator())#(b_plane_poly-prog_eps)*p.denominator()-p.numerator() #(b_plane_poly-prog_eps)*p.denominator()-p.numerator()
        elif leq_or_geq == 'geq':
            plane_polys[i] = p.numerator()+(b_plane_poly-1)*p.denominator()
        else:
            raise ValueError("leq_or_geq arg must be leq or geq not {}".format(leq_or_geq))  

    
    return plane_polys


def add_pair_constraint(geomA, geomB, prog, poly_to_cert, 
                        lagrange_mult_degree = 2, var_epsilon = None):
    VPolyA, VPolyB = VPolyhedronSets[geomA], VPolyhedronSets[geomB]
    print(VPolyA.vertices()-VPolyB.vertices())
    prog, a_plane_poly, b_plane_poly, dec_vars = construct_first_order_separating_hyperplane(prog, t)
        
    R_WA, p_WA = X_WA_multilinear_list[int(body_indexes_by_geom_id[geomA])]
    R_WB, p_WB  = X_WA_multilinear_list[int(body_indexes_by_geom_id[geomB])]
    
    base_point_poly = R_WA@VPolyA.vertices().mean(axis = 1)-p_WA
#     base_point = np.array([forward_kin.ConvertMultilinearPolynomialToRationalFunction(p) for p in base_point_poly])
    
    
    plane_polys_A = makeBodyHyperplaneSidePolynomials(prog, a_plane_poly, b_plane_poly, 
                                                     VPolyA, R_WA, p_WA , t, 
                                                     poly_to_cert, 'leq', lagrange_mult_degree,
                                                     var_epsilon, base_point_poly)
    plane_polys_B = makeBodyHyperplaneSidePolynomials(prog, a_plane_poly, b_plane_poly,
                                                     VPolyB, R_WB, p_WB , t, 
                                                     poly_to_cert, 'geq', lagrange_mult_degree,
                                                     var_epsilon, base_point_poly)
    plane_polys = plane_polys_A.tolist()+ plane_polys_B.tolist()

    for p in plane_polys:
        prog = putinarPsatConstraint(prog, p, t,  
                         poly_to_cert, lagrange_mult_degree = lagrange_mult_degree, var_epsilon = var_epsilon)
    return prog, plane_polys, (a_plane_poly, b_plane_poly), dec_vars

def certify_archimedean(poly_to_cert, t, lagrange_mult_degree = 2):
    convSolver = MosekSolver()
    prog = MathematicalProgram()
    prog.AddIndeterminates(t)
        
    t_bar = sym.Polynomial(t@t)

    poly = t_bar
    A = poly_to_cert.A()
    b = poly_to_cert.b()
    n = b.shape[0]
    for i in range(n):
        lagrange_poly, Q = prog.NewSosPolynomial(sym.Variables(t), lagrange_mult_degree)
        lagrange_poly.SetIndeterminates(sym.Variables(t))
        prog.AddSosConstraint(lagrange_poly)
        poly += lagrange_poly*sym.Polynomial(b[i] - A[i,:]@t)
    poly.SetIndeterminates(sym.Variables(t))
    prog.AddSosConstraint(poly)
    result = convSolver.Solve(prog)
    return result.is_success(), prog

def construct_region_safety_problem(poly_to_cert, lagrange_mult_degree = 2, var_epsilon = None, check_archimedean = True, plane_name = ""):
    
    if check_archimedean:
        is_Archimedean,_ = certify_archimedean(poly_to_cert, t)
        if not is_Archimedean:
            raise ValueError("region is not archimedean")
    prog = MathematicalProgram()
    prog.AddIndeterminates(t)
    plane_pairs = []
    plane_polys_list = []
    dec_vars = []
    for i, (geomA, geomB) in enumerate(pairs):
        print("pair {}/{}".format(i+1, len(pairs)))
        prog, plane_polys, (a_poly, b_poly), dec_vars0 = add_pair_constraint(geomA, geomB,
                                                       prog, poly_to_cert_safe,
                                                       lagrange_mult_degree = 4,
                                                       var_epsilon = eps*np.ones_like(poly_to_cert_safe.b())
                                                      )
        plane_polys_list.append(plane_polys)
        plane_pairs.append((a_poly, b_poly))
        dec_vars += dec_vars0
#         if i >= 1:
#             break
    return prog, plane_pairs, plane_polys_list, np.array(dec_vars)

def certify_region(poly_to_cert, lagrange_mult_degree = 4, var_epsilon = None, check_archimedean = True, numeric_tol = 1e-10):
    prog, plane_pairs, plane_polys_list, dec_vars = construct_region_safety_problem(poly_to_cert, 
                                                                          lagrange_mult_degree = lagrange_mult_degree, 
                                                                          var_epsilon = var_epsilon, 
                                                                          check_archimedean = check_archimedean)
    result = convSolver.Solve(prog)
    numerically_cert = result.is_success() and (np.linalg.norm(result.GetSolution())>= numeric_tol)
    print(np.linalg.norm(result.GetSolution()))
    return numerically_cert, result, prog
                                                      

In [20]:
#safe
prog = MathematicalProgram()
convSolver = MosekSolver()
prog.AddIndeterminates(t)
is_Archimedean,_ = certify_archimedean(poly_to_cert_safe, t)
print("Poly to cert safe is Archimedean {}".format(is_Archimedean))
safe = True
safe_failures = []

max_iter = 1
iter_num = 0

eps = 0
safe = False
plane_pairs = []
while iter_num < max_iter:
    prog, plane_pairs, plane_polys_list, dec_vars = construct_region_safety_problem(poly_to_cert_safe, 
                                    lagrange_mult_degree = 2, 
                                    var_epsilon = None, 
                                    check_archimedean = True, 
                                    plane_name = "")
    result = convSolver.Solve(prog)
    print("Var_epsilon = {}, safe = {}".format(eps, result.is_success()))
    if result.is_success():
        safe = True
        break
    else:
        eps += 0.1
        iter_num += 1
print("Safe = {}".format(result.is_success()))
print("Plane vars norm {}".format(np.linalg.norm(result.GetSolution(dec_vars))))
    
#     if not result.is_success():
#         safe_failures += (geomA, geomB)
#     safe = safe and result.is_success()
# print(safe)

Poly to cert safe is Archimedean True
pair 1/15
[[ 0.09   -0.09   -0.09    0.09    0.09   -0.09   -0.09    0.09  ]
 [-0.24   -0.24    0.24    0.24    0.24    0.24   -0.24   -0.24  ]
 [-0.4505 -0.4505 -0.4505 -0.4505 -0.3465 -0.3465 -0.3465 -0.3465]]
pair 2/15
[[-0.054  0.054  0.054 -0.054 -0.054  0.054  0.054 -0.054]
 [ 0.019  0.019 -0.019 -0.019 -0.019 -0.019  0.019  0.019]
 [-0.049 -0.049 -0.049 -0.049  0.051  0.051  0.051  0.051]]
pair 3/15
[[ 7.80625564e-18  6.07153217e-18  6.07153217e-18  7.80625564e-18
   7.80625564e-18  6.07153217e-18  6.07153217e-18  7.80625564e-18]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-3.46944695e-18 -3.46944695e-18  6.93889390e-18  6.93889390e-18
   3.46944695e-18  3.46944695e-18 -6.93889390e-18 -6.93889390e-18]]
pair 4/15
[[ 0.144   -0.144   -0.144    0.144    0.144   -0.144   -0.144    0.144  ]
 [-0.259   -0.259    0.259    0.259    0.259    0.259   -0.259   -0

In [21]:
for (a,b) in plane_pairs:
    for i in range(3):
        for a_coeff in a[i].decision_variables():
            print(result.GetSolution(a_coeff))
        for b_coeff in b.decision_variables():
            print(result.GetSolution(b_coeff))
    print()
res = result.GetSolution()
print(np.linalg.norm(res))

7.043660930082962e-08
8.175137520056567e-09
3.592616194239211e-09
14.393611572561715
-2.2325852429913356e-08
7.851739434280801e-09
-3.616200261214268e-09
-2.547627808348597
-8.000942325119265e-08
1.360446572757324e-08
8.548472634210099e-09
-7.677527903410974e-08
-2.2325852429913356e-08
7.851739434280801e-09
-3.616200261214268e-09
-2.547627808348597
8.967392393102898e-08
-2.7103367184540076e-08
1.7211944121481605e-08
-1.6276449276720475
-2.2325852429913356e-08
7.851739434280801e-09
-3.616200261214268e-09
-2.547627808348597

-2.2174207962732778e-09
-8.125609910058636e-10
3.4080821965428034e-11
4.496861430302376e-09
2.2461360960612338e-09
-1.3617480654571682e-09
-2.048071608233317e-09
0.9999999871986962
-5.5833546747968463e-08
7.906427534518705e-10
2.9955737274124207e-08
1.8714467436870816e-07
2.2461360960612338e-09
-1.3617480654571682e-09
-2.048071608233317e-09
0.9999999871986962
1.7031213190618451e-09
2.245775949098417e-09
6.868123277142864e-10
1.4191802492035278e-09
2.2461360960612338e

In [22]:
# unsafe
is_Archimedean,_ = certify_archimedean(poly_to_cert_unsafe, t)
print("Poly to cert safe is Archimedean {}".format(is_Archimedean))

# prog = MathematicalProgram()
# prog.AddIndeterminates(t)
# safe = True
# safe_failures = []
# prog = MathematicalProgram()
# prog.AddIndeterminates(t)
# plane_pairs = []
# plane_polys_list = []
prog, plane_pairs, plane_polys_list, dec_vars = construct_region_safety_problem(poly_to_cert_unsafe, 
                                    lagrange_mult_degree = 2, 
                                    var_epsilon = None, 
                                    check_archimedean = True, 
                                    plane_name = "")
result = convSolver.Solve(prog)
print("Safe = {}".format(result.is_success()))
print("Plane vars norm {}".format(np.linalg.norm(result.GetSolution(dec_vars))))

Poly to cert safe is Archimedean True
pair 1/15
[[ 0.09   -0.09   -0.09    0.09    0.09   -0.09   -0.09    0.09  ]
 [-0.24   -0.24    0.24    0.24    0.24    0.24   -0.24   -0.24  ]
 [-0.4505 -0.4505 -0.4505 -0.4505 -0.3465 -0.3465 -0.3465 -0.3465]]
pair 2/15
[[-0.054  0.054  0.054 -0.054 -0.054  0.054  0.054 -0.054]
 [ 0.019  0.019 -0.019 -0.019 -0.019 -0.019  0.019  0.019]
 [-0.049 -0.049 -0.049 -0.049  0.051  0.051  0.051  0.051]]
pair 3/15
[[ 7.80625564e-18  6.07153217e-18  6.07153217e-18  7.80625564e-18
   7.80625564e-18  6.07153217e-18  6.07153217e-18  7.80625564e-18]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-3.46944695e-18 -3.46944695e-18  6.93889390e-18  6.93889390e-18
   3.46944695e-18  3.46944695e-18 -6.93889390e-18 -6.93889390e-18]]
pair 4/15
[[ 0.144   -0.144   -0.144    0.144    0.144   -0.144   -0.144    0.144  ]
 [-0.259   -0.259    0.259    0.259    0.259    0.259   -0.259   -0

In [23]:
for (a,b) in plane_pairs:
    for i in range(3):
        for a_coeff in a[i].decision_variables():
            if np.abs(result.GetSolution(a_coeff)) > 1e-10:
                print(result.GetSolution(a_coeff))
        for b_coeff in b.decision_variables():
            if np.abs(result.GetSolution(b_coeff)) > 1e-10:
                print(result.GetSolution(b_coeff))
    print()
print("done")

7.043660930082962e-08
8.175137520056567e-09
3.592616194239211e-09
14.393611572561715
-2.2325852429913356e-08
7.851739434280801e-09
-3.616200261214268e-09
-2.547627808348597
-8.000942325119265e-08
1.360446572757324e-08
8.548472634210099e-09
-7.677527903410974e-08
-2.2325852429913356e-08
7.851739434280801e-09
-3.616200261214268e-09
-2.547627808348597
8.967392393102898e-08
-2.7103367184540076e-08
1.7211944121481605e-08
-1.6276449276720475
-2.2325852429913356e-08
7.851739434280801e-09
-3.616200261214268e-09
-2.547627808348597

-2.2174207962732778e-09
-8.125609910058636e-10
4.496861430302376e-09
2.2461360960612338e-09
-1.3617480654571682e-09
-2.048071608233317e-09
0.9999999871986962
-5.5833546747968463e-08
7.906427534518705e-10
2.9955737274124207e-08
1.8714467436870816e-07
2.2461360960612338e-09
-1.3617480654571682e-09
-2.048071608233317e-09
0.9999999871986962
1.7031213190618451e-09
2.245775949098417e-09
6.868123277142864e-10
1.4191802492035278e-09
2.2461360960612338e-09
-1.3617480654571682

In [24]:
res = result.GetSolution()
print(np.linalg.norm(res))

366.079108927801


In [25]:
print(np.array(plane_polys_list).shape)

(15, 16)


In [ ]:

convSolver = MosekSolver()
is_Archimedean,_ = certify_archimedean(poly_to_cert_unsafe, t)
print("Poly to cert safe is Archimedean {}".format(is_Archimedean))
start_time = time.time()
failures = []
for j,r in enumerate(regions):
    print("Region {}/{}".format(j, len(regions)-1))
    rtmp = HPolyhedron(r.A(), r.b()+0.5)
    numerically_cert, result, prog = certify_region(rtmp, 
                                                    lagrange_mult_degree = 4,
                                                    check_archimedean = True,
                                                    numeric_tol = 1e-10)
    print("Safe: {}".format(numerically_cert))
    if not numerically_cert:
        failures += [r]
end_time = time.time()
print("Certified in {}".format(end_time-start_time))

Poly to cert safe is Archimedean True
Region 0/5
pair 1/15
[[ 0.09   -0.09   -0.09    0.09    0.09   -0.09   -0.09    0.09  ]
 [-0.24   -0.24    0.24    0.24    0.24    0.24   -0.24   -0.24  ]
 [-0.4505 -0.4505 -0.4505 -0.4505 -0.3465 -0.3465 -0.3465 -0.3465]]
pair 2/15
[[-0.054  0.054  0.054 -0.054 -0.054  0.054  0.054 -0.054]
 [ 0.019  0.019 -0.019 -0.019 -0.019 -0.019  0.019  0.019]
 [-0.049 -0.049 -0.049 -0.049  0.051  0.051  0.051  0.051]]
pair 3/15
[[ 7.80625564e-18  6.07153217e-18  6.07153217e-18  7.80625564e-18
   7.80625564e-18  6.07153217e-18  6.07153217e-18  7.80625564e-18]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-3.46944695e-18 -3.46944695e-18  6.93889390e-18  6.93889390e-18
   3.46944695e-18  3.46944695e-18 -6.93889390e-18 -6.93889390e-18]]
pair 4/15
[[ 0.144   -0.144   -0.144    0.144    0.144   -0.144   -0.144    0.144  ]
 [-0.259   -0.259    0.259    0.259    0.259    0.259   

pair 5/15
[[ 0.077   -0.077   -0.077    0.077    0.077   -0.077   -0.077    0.077  ]
 [-0.26375 -0.26375  0.26375  0.26375  0.26375  0.26375 -0.26375 -0.26375]
 [-0.4165  -0.4165  -0.4165  -0.4165  -0.3825  -0.3825  -0.3825  -0.3825 ]]
pair 6/15
[[ 0.077   -0.077   -0.077    0.077    0.077   -0.077   -0.077    0.077  ]
 [-0.26375 -0.26375  0.26375  0.26375  0.26375  0.26375 -0.26375 -0.26375]
 [-0.14815 -0.14815 -0.14815 -0.14815 -0.11415 -0.11415 -0.11415 -0.11415]]
pair 7/15
[[ 0.144  -0.144  -0.144   0.144   0.144  -0.144  -0.144   0.144 ]
 [-0.259  -0.259   0.259   0.259   0.259   0.259  -0.259  -0.259 ]
 [-0.4015 -0.4015 -0.4015 -0.4015 -0.3975 -0.3975 -0.3975 -0.3975]]
pair 8/15
[[ 0.144  -0.144  -0.144   0.144   0.144  -0.144  -0.144   0.144 ]
 [-0.259  -0.259   0.259   0.259   0.259   0.259  -0.259  -0.259 ]
 [-0.4015 -0.4015 -0.4015 -0.4015 -0.3975 -0.3975 -0.3975 -0.3975]]
pair 9/15
[[ 0.09    -0.09    -0.09     0.09     0.09    -0.09    -0.09     0.09   ]
 [-0.24    -0.24   

In [ ]:
# certify region is P compact

archimedean_safe, _  = certify_archimedean(poly_to_cert_safe, t)
archimedean_unsafe, _  = certify_archimedean(poly_to_cert_unsafe, t)
print(archimedean_safe)
print(archimedean_unsafe)

# Comments with Hongkai
1.) To reduce poly size always get transforms relative to middle link in kinematic chain between two bodies (not worried)

2.) make the hyperplane an affine function of t. Should allow plane to rotate

3.) Do line search on Ct <= b- epsilon to scale regions

4.) Rational polynomials should have coordinate degree 2. Track down this bug ASAP
